import type { RawSheetData } from "./sheets";

export function getMockData(): RawSheetData {
  return {
    teams: [
      ["Team Name", "Logo"],
      ["Mariners FC", ""],
      ["Fenix FC", ""],
      ["Hygge SC", ""],
      ["FC Torpedo", ""],
    ],
    roster: [
      ["Picture", "Player Name", "Team", "Pref. Pos.", "MD1", "MD2", "MD3", "MD4", "MD5", "MD6", "MD7", "MD8"],
      // Mariners FC
      ["", "Yas Makita", "Mariners FC", "GK", "Expected", "", "", "", "", "", "", ""],
      ["", "Isen", "Mariners FC", "DF", "Expected", "", "", "", "", "", "", ""],
      ["", "Ken Hirami", "Mariners FC", "DF", "Y", "", "", "", "", "", "", ""],
      ["", "Kevin Chang", "Mariners FC", "DF/MF", "Y", "", "", "", "", "", "", ""],
      ["", "Merck", "Mariners FC", "MF", "Y", "", "", "", "", "", "", ""],
      ["", "Stefan", "Mariners FC", "MF", "Y", "", "", "", "", "", "", ""],
      ["", "Ian Noseda", "Mariners FC", "MF/FWD", "Y", "", "", "", "", "", "", ""],
      ["", "Yusuke", "Mariners FC", "MF", "Y", "", "", "", "", "", "", ""],
      ["", "Nathan Chang", "Mariners FC", "FWD", "Y", "", "", "", "", "", "", ""],
      ["", "Laurence", "Mariners FC", "MF/FWD", "Y", "", "", "", "", "", "", ""],
      ["", "Vernieri Luca", "Mariners FC", "FWD", "Y", "", "", "", "", "", "", ""],
      ["", "Taka", "Mariners FC", "MF", "", "", "", "", "", "", "", ""],
      ["", "Taro", "Mariners FC", "DF", "", "", "", "", "", "", "", ""],
      // Fenix FC
      ["", "Ivo Rodrigues", "Fenix FC", "GK", "Y", "", "", "", "", "", "", ""],
      ["", "Ryota Itou", "Fenix FC", "DF", "Y", "", "", "", "", "", "", ""],
      ["", "Kentaro Morooka", "Fenix FC", "DF", "Y", "", "", "", "", "", "", ""],
      ["", "Miguel", "Fenix FC", "MF", "Y", "", "", "", "", "", "", ""],
      ["", "Ryuusei", "Fenix FC", "MF", "Y", "", "", "", "", "", "", ""],
      ["", "Badr", "Fenix FC", "MF/FWD", "Y", "", "", "", "", "", "", ""],
      ["", "Shu Yoshimura", "Fenix FC", "FWD", "Y", "", "", "", "", "", "", ""],
      ["", "Shishido Ken", "Fenix FC", "DF/MF", "Y", "", "", "", "", "", "", ""],
      ["", "Kosma Knasiecki", "Fenix FC", "MF", "Y", "", "", "", "", "", "", ""],
      ["", "Alexander Vassiliev", "Fenix FC", "FWD", "Y", "", "", "", "", "", "", ""],
      ["", "Johannes", "Fenix FC", "MF", "Y", "", "", "", "", "", "", ""],
      ["", "Vitor", "Fenix FC", "MF/FWD", "", "", "", "", "", "", "", ""],
      ["", "Hiro Tanaka", "Fenix FC", "DF", "", "", "", "", "", "", "", ""],
      // Hygge SC
      ["", "Ryohei Enomoto", "Hygge SC", "GK", "Y", "", "", "", "", "", "", ""],
      ["", "Ben Lee", "Hygge SC", "DF", "Y", "", "", "", "", "", "", ""],
      ["", "Sebastien Gaboriau", "Hygge SC", "DF/MF", "Y", "", "", "", "", "", "", ""],
      ["", "Khrapov Tymur", "Hygge SC", "MF", "Y", "", "", "", "", "", "", ""],
      ["", "Nikolai Akira Kawabata", "Hygge SC", "MF", "Y", "", "", "", "", "", "", ""],
      ["", "Fatih Emre", "Hygge SC", "MF/FWD", "Y", "", "", "", "", "", "", ""],
      ["", "Enes Komuro", "Hygge SC", "FWD", "Y", "", "", "", "", "", "", ""],
      ["", "Player K", "Hygge SC", "MF", "Y", "", "", "", "", "", "", ""],
      ["", "Player S", "Hygge SC", "FWD", "Y", "", "", "", "", "", "", ""],
      ["", "Daichi", "Hygge SC", "DF", "", "", "", "", "", "", "", ""],
      ["", "Yuto", "Hygge SC", "MF", "", "", "", "", "", "", "", ""],
      ["", "Takumi", "Hygge SC", "FWD", "", "", "", "", "", "", "", ""],
      // FC Torpedo
      ["", "Alex Kim", "FC Torpedo", "", "", "", "", "", "", "", "", ""],
      ["", "James Park", "FC Torpedo", "", "", "", "", "", "", "", "", ""],
      ["", "Kenji Yamamoto", "FC Torpedo", "", "", "", "", "", "", "", "", ""],
      ["", "Marco Silva", "FC Torpedo", "", "", "", "", "", "", "", "", ""],
      ["", "Ryu Tanaka", "FC Torpedo", "", "", "", "", "", "", "", "", ""],
      ["", "Sato Hiroshi", "FC Torpedo", "", "", "", "", "", "", "", "", ""],
      ["", "Tom Wilson", "FC Torpedo", "", "", "", "", "", "", "", "", ""],
      ["", "Yuki Abe", "FC Torpedo", "", "", "", "", "", "", "", "", ""],
      ["", "Carlos Dias", "FC Torpedo", "", "", "", "", "", "", "", "", ""],
      ["", "Daisuke Ono", "FC Torpedo", "", "", "", "", "", "", "", "", ""],
      ["", "Erik Svensson", "FC Torpedo", "", "", "", "", "", "", "", "", ""],
      ["", "Fumiya Ito", "FC Torpedo", "", "", "", "", "", "", "", "", ""],
      ["", "George Chen", "FC Torpedo", "", "", "", "", "", "", "", "", ""],
    ],
    schedule: [
      ["Matchday", "Match", "Kickoff Time", "Full Time", "Home Team", "Away Team"],
      // MD1
      ["MD1", "1", "19:05", "19:38", "Mariners FC", "Hygge SC"],
      ["MD1", "2", "19:40", "20:13", "Mariners FC", "Fenix FC"],
      ["MD1", "3", "20:15", "20:48", "Hygge SC", "Fenix FC"],
      // MD2
      ["MD2", "1", "19:05", "19:38", "Fenix FC", "FC Torpedo"],
      ["MD2", "2", "19:40", "20:13", "Fenix FC", "Mariners FC"],
      ["MD2", "3", "20:15", "20:48", "FC Torpedo", "Mariners FC"],
      // MD3
      ["MD3", "1", "19:05", "19:38", "Hygge SC", "Mariners FC"],
      ["MD3", "2", "19:40", "20:13", "Hygge SC", "FC Torpedo"],
      ["MD3", "3", "20:15", "20:48", "Mariners FC", "FC Torpedo"],
      // MD4
      ["MD4", "1", "19:05", "19:38", "FC Torpedo", "Hygge SC"],
      ["MD4", "2", "19:40", "20:13", "FC Torpedo", "Fenix FC"],
      ["MD4", "3", "20:15", "20:48", "Hygge SC", "Fenix FC"],
      // MD5
      ["MD5", "1", "19:05", "19:38", "Mariners FC", "Hygge SC"],
      ["MD5", "2", "19:40", "20:13", "Mariners FC", "Fenix FC"],
      ["MD5", "3", "20:15", "20:48", "Hygge SC", "Fenix FC"],
      // MD6
      ["MD6", "1", "19:05", "19:38", "Fenix FC", "FC Torpedo"],
      ["MD6", "2", "19:40", "20:13", "Fenix FC", "Mariners FC"],
      ["MD6", "3", "20:15", "20:48", "FC Torpedo", "Mariners FC"],
      // MD7
      ["MD7", "1", "19:05", "19:38", "Hygge SC", "Mariners FC"],
      ["MD7", "2", "19:40", "20:13", "Hygge SC", "FC Torpedo"],
      ["MD7", "3", "20:15", "20:48", "Mariners FC", "FC Torpedo"],
      // MD8
      ["MD8", "1", "19:05", "19:38", "FC Torpedo", "Hygge SC"],
      ["MD8", "2", "19:40", "20:13", "FC Torpedo", "Fenix FC"],
      ["MD8", "3", "20:15", "20:48", "Hygge SC", "Fenix FC"],
    ],
    goals: [
      ["MD", "Timestamp", "Scoring Team", "Conceding Team", "Scorer", "Assister"],
      // MD1 Match 1: Mariners FC 2 - 2 Hygge SC
      ["MD1", "2026-04-03T10:10:00", "Mariners FC", "Hygge SC", "Ian Noseda", "Laurence"],
      ["MD1", "2026-04-03T10:15:00", "Hygge SC", "Mariners FC", "Fatih Emre", "Enes Komuro"],
      ["MD1", "2026-04-03T10:22:00", "Mariners FC", "Hygge SC", "Vernieri Luca", "Ian Noseda"],
      ["MD1", "2026-04-03T10:30:00", "Hygge SC", "Mariners FC", "Enes Komuro", "Ben Lee"],
      // MD1 Match 2: Mariners FC 2 - 2 Fenix FC
      ["MD1", "2026-04-03T10:45:00", "Mariners FC", "Fenix FC", "Ian Noseda", "Nathan Chang"],
      ["MD1", "2026-04-03T10:50:00", "Fenix FC", "Mariners FC", "Badr", "Miguel"],
      ["MD1", "2026-04-03T10:55:00", "Fenix FC", "Mariners FC", "Shu Yoshimura", "Badr"],
      ["MD1", "2026-04-03T11:00:00", "Mariners FC", "Fenix FC", "Nathan Chang", "Stefan"],
      // MD1 Match 3: Hygge SC 4 - 3 Fenix FC
      ["MD1", "2026-04-03T11:20:00", "Hygge SC", "Fenix FC", "Fatih Emre", "Nikolai Akira Kawabata"],
      ["MD1", "2026-04-03T11:25:00", "Fenix FC", "Hygge SC", "Badr", "Kosma Knasiecki"],
      ["MD1", "2026-04-03T11:28:00", "Hygge SC", "Fenix FC", "Enes Komuro", ""],
      ["MD1", "2026-04-03T11:32:00", "Fenix FC", "Hygge SC", "Alexander Vassiliev", ""],
      ["MD1", "2026-04-03T11:35:00", "Hygge SC", "Fenix FC", "Guest", "Fatih Emre"],
      ["MD1", "2026-04-03T11:40:00", "Fenix FC", "Hygge SC", "Shu Yoshimura", "Ryuusei"],
      ["MD1", "2026-04-03T11:43:00", "Hygge SC", "Fenix FC", "Nikolai Akira Kawabata", "Sebastien Gaboriau"],
    ],
    ratings: [
      // Header: MD, Timestamp, Team, then player names (simplified for mock), then 4 meta cols
      ["MD", "Timestamp", "Team",
        "Yas Makita", "Isen", "Ken Hirami", "Kevin Chang", "Merck", "Stefan",
        "Ian Noseda", "Nathan Chang", "Laurence", "Vernieri Luca",
        "Refereeing", "Games Close", "Teamwork", "Enjoyment"],
      // A Mariners player rating their own team
      ["MD1", "2026-04-03T12:00:00", "Blue Mariners FC",
        "4", "4", "4", "3", "3", "3", "5", "4", "4", "5",
        "4", "5", "4", "5"],
      ["MD1", "2026-04-03T12:05:00", "Blue Mariners FC",
        "3", "4", "3", "4", "3", "4", "5", "4", "3", "4",
        "4", "4", "4", "5"],
    ],
    scheduleFormula: [
      ["Matchday", "First", "Middle", "Last", "Sits Out"],
      ["MD1", "Mariners FC", "Hygge SC", "Fenix FC", "FC Torpedo"],
      ["MD2", "Fenix FC", "FC Torpedo", "Mariners FC", "Hygge SC"],
      ["MD3", "Hygge SC", "Mariners FC", "FC Torpedo", "Fenix FC"],
      ["MD4", "FC Torpedo", "Hygge SC", "Fenix FC", "Mariners FC"],
      ["MD5", "Mariners FC", "Hygge SC", "Fenix FC", "FC Torpedo"],
      ["MD6", "Fenix FC", "FC Torpedo", "Mariners FC", "Hygge SC"],
      ["MD7", "Hygge SC", "Mariners FC", "FC Torpedo", "Fenix FC"],
      ["MD8", "FC Torpedo", "Hygge SC", "Fenix FC", "Mariners FC"],
    ],
    mdSchedule: [
      ["Matchday", "Date"],
      ["MD1", "2026-04-03"],
      ["MD2", "2026-04-10"],
      ["MD3", "2026-04-17"],
      ["MD4", "2026-04-24"],
      ["MD5", "2026-05-01"],
      ["MD6", "2026-05-08"],
      ["MD7", "2026-05-15"],
      ["MD8", "2026-05-22"],
    ],
  };
}
