-- v1.93.0 — Replace the v1.91.0 count-only `MatchdayGuestEntry` with
-- per-row `MatchdayGuest`. Each entry row's (externalCount + leagueCount)
-- pair becomes that many MatchdayGuest rows (one per guest, typed).
--
-- DDL was generated by `prisma migrate diff --from-schema-datamodel <pre>
-- --to-schema-datamodel <post> --script` (offline; no DB connection
-- needed) per the v1.86.1 post-mortem rule (`docs/migration-sql-lessons.md`).
-- Prisma's natural emit order is DROP OLD → CREATE NEW; we reorder to
-- CREATE NEW → INSERT BACKFILL → DROP OLD so the backfill runs atomically
-- within the same migration. The DDL statements themselves are byte-for-
-- byte what Prisma emitted (verified by hand). The two INSERT statements
-- are pure-data backfills (permitted exception per migration-sql-lessons.md)
-- and reference Prisma-generated table + column names exactly as emitted.
--
-- Prod state as of v1.92.0 deploy: `SELECT COUNT(*) FROM "MatchdayGuestEntry"`
-- returns 0 (the v1.91.0 feature shipped but no user submitted any guests
-- before the redesign). The backfill is therefore a no-op on prod. It
-- still exists so a non-prod environment (preview, dev DB, future
-- replay) with rows in the old table migrates losslessly into the new
-- shape without operator intervention.

-- CreateEnum
CREATE TYPE "GuestType" AS ENUM ('EXTERNAL', 'LEAGUE');

-- CreateTable
CREATE TABLE "MatchdayGuest" (
    "id" TEXT NOT NULL,
    "gameWeekId" TEXT NOT NULL,
    "leagueTeamId" TEXT NOT NULL,
    "type" "GuestType" NOT NULL,
    "positions" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "displayOrder" INTEGER NOT NULL DEFAULT 0,
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MatchdayGuest_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "MatchdayGuest_gameWeekId_leagueTeamId_type_idx" ON "MatchdayGuest"("gameWeekId", "leagueTeamId", "type");

-- CreateIndex
CREATE INDEX "MatchdayGuest_gameWeekId_idx" ON "MatchdayGuest"("gameWeekId");

-- CreateIndex
CREATE INDEX "MatchdayGuest_leagueTeamId_idx" ON "MatchdayGuest"("leagueTeamId");

-- AddForeignKey
ALTER TABLE "MatchdayGuest" ADD CONSTRAINT "MatchdayGuest_gameWeekId_fkey" FOREIGN KEY ("gameWeekId") REFERENCES "GameWeek"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MatchdayGuest" ADD CONSTRAINT "MatchdayGuest_leagueTeamId_fkey" FOREIGN KEY ("leagueTeamId") REFERENCES "LeagueTeam"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MatchdayGuest" ADD CONSTRAINT "MatchdayGuest_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Backfill: external guests. Each MatchdayGuestEntry row with externalCount > 0
-- becomes that many EXTERNAL MatchdayGuest rows, indexed 0..N-1 via displayOrder.
-- gen_random_uuid() is a Postgres-13 built-in; Neon runs PG ≥15. The id is
-- prefixed "mg-" purely as a debug aid (matches the project's id-prefix
-- convention from src/lib/ids.ts). No-op when source table is empty.
INSERT INTO "MatchdayGuest" ("id", "gameWeekId", "leagueTeamId", "type", "positions", "displayOrder", "createdById", "createdAt", "updatedAt")
SELECT
    'mg-' || replace(gen_random_uuid()::text, '-', ''),
    e."gameWeekId",
    e."leagueTeamId",
    'EXTERNAL'::"GuestType",
    ARRAY[]::TEXT[],
    s.i - 1,
    e."createdById",
    e."createdAt",
    e."updatedAt"
FROM "MatchdayGuestEntry" e
CROSS JOIN LATERAL generate_series(1, e."externalCount") AS s(i)
WHERE e."externalCount" > 0;

-- Backfill: league guests. Same shape, type=LEAGUE.
INSERT INTO "MatchdayGuest" ("id", "gameWeekId", "leagueTeamId", "type", "positions", "displayOrder", "createdById", "createdAt", "updatedAt")
SELECT
    'mg-' || replace(gen_random_uuid()::text, '-', ''),
    e."gameWeekId",
    e."leagueTeamId",
    'LEAGUE'::"GuestType",
    ARRAY[]::TEXT[],
    s.i - 1,
    e."createdById",
    e."createdAt",
    e."updatedAt"
FROM "MatchdayGuestEntry" e
CROSS JOIN LATERAL generate_series(1, e."leagueCount") AS s(i)
WHERE e."leagueCount" > 0;

-- DropForeignKey
ALTER TABLE "MatchdayGuestEntry" DROP CONSTRAINT "MatchdayGuestEntry_gameWeekId_fkey";

-- DropForeignKey
ALTER TABLE "MatchdayGuestEntry" DROP CONSTRAINT "MatchdayGuestEntry_leagueTeamId_fkey";

-- DropForeignKey
ALTER TABLE "MatchdayGuestEntry" DROP CONSTRAINT "MatchdayGuestEntry_createdById_fkey";

-- DropTable
DROP TABLE "MatchdayGuestEntry";
